image:
  repository: quay.io/opendatahub/odh-ray-module-operator
  tag: latest
  pullPolicy: IfNotPresent

operatorNamespace: ray-module-operator-system
applicationsNamespace: opendatahub

relatedImages:
  kuberayOperator: quay.io/opendatahub/kuberay-operator:latest
  kubeRbacProxy: quay.io/opendatahub/odh-kube-rbac-proxy:odh-stable

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 10m
    memory: 256Mi
