apiVersion: components.platform.opendatahub.io/v1alpha1
kind: Ray
metadata:
  labels:
    app.kubernetes.io/name: ray-module-operator
    app.kubernetes.io/managed-by: kustomize
  name: ray-sample
spec:
  # TODO(user): Add fields here
